# Generated by Django 3.2.4 on 2021-09-06 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20200428_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user_updated',
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=150)),
                ('archivo_propuesta', models.FileField(upload_to='perfilpdf/')),
                ('solicitud_persona', models.FileField(upload_to='perfilpdf/')),
                ('solicitud_material', models.FileField(upload_to='perfilpdf/')),
                ('descripcion', models.TextField(max_length=255)),
                ('fecha_registro', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nuevo', models.BooleanField()),
                ('cumplido', models.BooleanField()),
                ('proceso', models.BooleanField()),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
    ]
