# Generated by Django 3.2.4 on 2021-09-07 23:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_client_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=150, verbose_name='Proyecto')),
                ('offer', models.FileField(upload_to='perfilpdf/', verbose_name='Archivo Propuesta')),
                ('request_personal', models.FileField(upload_to='perfilpdf/', verbose_name='Solicitud de persona')),
                ('request_material', models.FileField(upload_to='perfilpdf/', verbose_name='Solicitud de material')),
                ('description', models.TextField(max_length=255, verbose_name='Descripción')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_start', models.DateField(verbose_name='Fecha de inicio')),
                ('date_finish', models.DateField(verbose_name='fecha de finalización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('process', models.BooleanField(verbose_name='Proceso')),
                ('represent', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Representante')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Proyect',
        ),
    ]
