# Generated by Django 3.2.4 on 2021-09-09 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210907_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quantity_pro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Archivo Propuesta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='represent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_material',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Solicitud de material'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_personal',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Solicitud de personal'),
        ),
    ]
