# Generated by Django 3.2.4 on 2021-09-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20210908_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='quantity_pro',
            new_name='quantity',
        ),
    ]
