# Generated by Django 3.2.4 on 2021-09-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_rename_quantity_pro_project_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
