# Generated by Django 3.2.7 on 2021-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
