# Generated by Django 3.2.7 on 2021-11-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='academic',
            field=models.CharField(default=1, max_length=150, verbose_name='Título Academico'),
            preserve_default=False,
        ),
    ]
