# Generated by Django 3.2.7 on 2021-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20211106_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='Entidad'),
        ),
    ]
