# Generated by Django 3.2.7 on 2021-11-07 23:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20211106_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='managed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='oespecific1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ogeneral',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, max_length=60000, verbose_name='Contenidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=ckeditor.fields.RichTextField(default=2, max_length=10000, verbose_name='Introducción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TimeField(max_length=255, verbose_name='Descripción'),
        ),
    ]
