# Generated by Django 3.2.7 on 2021-11-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20211107_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=1, max_length=60000, verbose_name='Contenidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(default=1, max_length=10000, verbose_name='Introducción'),
            preserve_default=False,
        ),
    ]
