# Generated by Django 3.2.7 on 2021-11-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_auto_20211107_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='contentpro',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='introduction',
            new_name='introductionpro',
        ),
    ]
