# Generated by Django 3.2.7 on 2021-11-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_auto_20211107_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managed',
            field=models.CharField(default=1, max_length=150, verbose_name='Introduccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ogeneral',
            field=models.CharField(default=1, max_length=150, verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
