# Generated by Django 3.2.7 on 2021-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20211107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=models.CharField(max_length=15000, verbose_name='Introduccion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ogeneral',
            field=models.CharField(max_length=65000, verbose_name='Contenido'),
        ),
    ]
