# Generated by Django 3.2.7 on 2021-11-08 20:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_auto_20211107_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=ckeditor.fields.RichTextField(max_length=20000, verbose_name='Introduccion'),
        ),
    ]
