# Generated by Django 3.2.7 on 2021-11-10 15:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_alter_project_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=20000, verbose_name='Introduccion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ogeneral',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=65000, verbose_name='Contenido'),
        ),
    ]
