# Generated by Django 3.2.7 on 2021-11-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_auto_20211110_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='oespecific1',
            field=models.CharField(default=1, max_length=150, verbose_name='Objetivo Específico 1'),
            preserve_default=False,
        ),
    ]
