# Generated by Django 3.2.7 on 2021-11-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_project_oespecific1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='oespecific1',
        ),
    ]
