# Generated by Django 3.2.7 on 2021-11-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_remove_project_oespecific1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='represent',
            field=models.CharField(max_length=150, verbose_name='Representante'),
        ),
    ]
