# Generated by Django 3.2.7 on 2021-11-13 17:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_project_represent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quantity_mount',
            field=models.CharField(default=1, max_length=150, verbose_name='Detalle del Monto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=20000, verbose_name='Antecedentes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='Entidad Ejecutora'),
        ),
        migrations.AlterField(
            model_name='project',
            name='represent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Administrador de Proyecto'),
        ),
    ]
