# Generated by Django 3.2.7 on 2021-11-13 22:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_auto_20211113_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reshumans',
            field=models.CharField(default=1, max_length=150, verbose_name='Recursos Humanos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=20000, verbose_name='Antecedentes del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ogeneral',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=65000, verbose_name='Detalle del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto del Proyecto'),
        ),
    ]
