# Generated by Django 3.2.7 on 2021-11-16 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_auto_20211113_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Represent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='represent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.represent', verbose_name='Administrador de Proyecto'),
        ),
    ]
