# Generated by Django 3.2.7 on 2021-11-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_auto_20211116_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='represent',
            old_name='names',
            new_name='namesr',
        ),
    ]
