# Generated by Django 3.2.7 on 2021-11-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_rename_represent_project_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='represent',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='represent',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
        migrations.AddField(
            model_name='represent',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
    ]
