# Generated by Django 3.2.7 on 2021-11-17 00:19

import core.erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_auto_20211116_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Maximum file size allowed is 2Mb', null=True, upload_to='product/%Y/%m/%d', validators=[core.erp.models.validate_image], verbose_name='Imagen'),
        ),
    ]
