# Generated by Django 3.2.7 on 2021-11-17 01:15

import core.erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0040_auto_20211116_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='El tamaño máximo de archivo permitido es 2Mb', null=True, upload_to='product/%Y/%m/%d', validators=[core.erp.models.validate_image], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='dni',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='namesr',
            field=models.SlugField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
    ]
