# Generated by Django 3.2.7 on 2021-11-18 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_auto_20211116_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo Propuesta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_material',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de material'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_personal',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de personal'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='namesr',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 2'),
        ),
    ]
