# Generated by Django 3.2.7 on 2021-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_alter_represent_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='represent',
            name='dni',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
