# Generated by Django 3.2.7 on 2021-11-19 18:06

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_alter_represent_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construcction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Proyecto del Proyecto')),
                ('organization', models.CharField(max_length=250, verbose_name='Entidad Ejecutora')),
                ('benefits', models.CharField(max_length=2000, verbose_name='Cliente Beneficiario')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto del Proyecto')),
                ('detail_amount', models.CharField(max_length=150, verbose_name='Detalle del Monto')),
                ('reshumans', models.CharField(max_length=1000, verbose_name='Recursos Humanos')),
                ('resmaterials', models.CharField(max_length=1000, verbose_name='Recursos Materiales')),
                ('managed', ckeditor_uploader.fields.RichTextUploadingField(max_length=20000, verbose_name='Antecedentes del Proyecto')),
                ('ogeneral', ckeditor_uploader.fields.RichTextUploadingField(max_length=65000, verbose_name='Detalle del Proyecto')),
                ('offer', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo Propuesta')),
                ('request_personal', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de personal')),
                ('request_material', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de material')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateField(default=datetime.datetime.now, verbose_name='fecha de finalización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('process', models.BooleanField(verbose_name='Proceso')),
                ('results', models.CharField(max_length=5000, verbose_name='Resultados')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.CharField(default=1, max_length=5000, verbose_name='Resultados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='represent',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='represent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='represent',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='represent',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.sale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='represent',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='DetMaterialsConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.construcction')),
            ],
        ),
        migrations.CreateModel(
            name='DetMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project')),
            ],
        ),
        migrations.CreateModel(
            name='DetHumansConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.construcction')),
            ],
        ),
        migrations.CreateModel(
            name='DetHumans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project')),
            ],
        ),
        migrations.AddField(
            model_name='construcction',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.represent', verbose_name='Administrador de Proyecto'),
        ),
    ]
