# Generated by Django 3.2.7 on 2021-11-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0052_auto_20211119_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construcction',
            old_name='name',
            new_name='namec',
        ),
    ]
