# Generated by Django 3.2.7 on 2021-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_rename_name_construcction_namec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='represent',
            name='cant',
        ),
        migrations.RemoveField(
            model_name='represent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='represent',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='represent',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='represent',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(max_length=10, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='dni',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula Cédula de Identidad'),
        ),
    ]
