# Generated by Django 3.2.7 on 2021-11-22 21:59

import core.erp.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_auto_20211119_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Cargo')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción del Cargo')),
                ('area', models.CharField(blank=True, max_length=500, null=True, verbose_name='Area estretégica del Cargo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.IntegerField(max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('image', models.ImageField(blank=True, help_text='El tamaño máximo de archivo permitido es 2Mb', null=True, upload_to='employer/%Y/%m/%d', validators=[core.erp.models.validate_image], verbose_name='Imagen')),
                ('phone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 2')),
                ('phone3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número alterno emergencia')),
                ('date_birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('City', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ciudad')),
                ('Country', models.CharField(blank=True, max_length=150, null=True, verbose_name='País')),
                ('nationality', models.CharField(max_length=150, verbose_name='Nacionalidad')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Hoja de Vida')),
                ('health_card', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Ficha Médica')),
                ('memorandum_ontract', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Memorando de Contratación o Autorización')),
                ('resignation', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de renuncia o Solicitudd de salida')),
                ('enabling_document', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento Habilitante Liquidación')),
                ('holidays', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de Vacaciones')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateField(default=datetime.datetime.now, verbose_name='fecha de finalización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.position', verbose_name='Cargo a ocupar')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
