# Generated by Django 3.2.7 on 2021-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_auto_20211123_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='memorandum_ontract',
            new_name='memorandum_contract',
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone1',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 1'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone2',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número telefónico 2'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone3',
            field=models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número alterno emergencia'),
        ),
    ]
