# Generated by Django 3.2.7 on 2021-12-01 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0058_alter_represent_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethumans',
            name='annexes',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Anexos, Fotografías, Etc...'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='application',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de Contratación'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='autorization',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Autorización de Contratación'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='budget_certification',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación Presupuestaria'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='budget_request',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de Contratación Presupuestaria'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='enabling_documents',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documentos Habilitantes'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='pay_order',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Orden de Pago'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='payment_memorandum',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Memorando de Pago'),
        ),
        migrations.AddField(
            model_name='dethumans',
            name='report_satisfaction',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe Satisfacción/Productos Generados'),
        ),
        migrations.AlterField(
            model_name='dethumans',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Personal contratado'),
        ),
        migrations.AlterField(
            model_name='dethumans',
            name='observations',
            field=models.CharField(max_length=1000, verbose_name='Observaciones de proyecto'),
        ),
        migrations.AlterField(
            model_name='dethumans',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione Nombre del Proyecto'),
        ),
    ]
