# Generated by Django 3.2.7 on 2021-12-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_auto_20211130_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetHumans',
            new_name='Servicesp',
        ),
    ]
