# Generated by Django 3.2.7 on 2021-12-02 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_rename_dethumans_servicesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisitionbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto proyecto')),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones de proyecto')),
                ('application', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud requirente - proyecto')),
                ('study', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Estudio de necesidad')),
                ('proforms', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Estudio de mercado / 3 proformas (archivo comprimido)')),
                ('autorization', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Autorización de solicitud de compra')),
                ('budget_request', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de certificación presupuestaria')),
                ('budget_certification', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación presupuestaria')),
                ('certification_pac', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación PAC')),
                ('certification_not_exist', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación NO EXISTE en catálogo electrónico')),
                ('report_satisfaction', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de satisfacción / Requirente proyecto')),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Orden de compra')),
                ('delivery_certificate', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Acta entrega - recepción proveedor')),
                ('entry_egress', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Ingreso - Egreso de bodega')),
                ('enabling_documents', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documentos Habilitantes: RUC - CERT BANCARIA- COPIA CÉDULA')),
                ('payment_memorandum', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Memorando de Pago')),
                ('pay_order', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Orden de Pago')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Factura Electrónica mayor a 1000 USD')),
                ('construcction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.construcction', verbose_name='Seleccione nombre del proyecto')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione nombre del proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='annexes',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Anexos, fotografías, etc...'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='application',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de contratación'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='autorization',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Autorización de contratación'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='budget_certification',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación presupuestaria'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='budget_request',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de contratación presupuestaria'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='enabling_documents',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documentos habilitantes: RUC - CERT BANCARIA- COPIA CÉDULA'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Factura electrónica mayor a 1000 USD'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='pay_order',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Orden de pago'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='payment_memorandum',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Memorando de pago'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto proyecto'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='report_satisfaction',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe satisfacción / Productos generados'),
        ),
        migrations.DeleteModel(
            name='DetMaterials',
        ),
    ]
