# Generated by Django 3.2.7 on 2021-12-02 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_auto_20211202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionbs',
            name='construcction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.construcction', verbose_name='Seleccione nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='acquisitionbs',
            name='personal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione nombre del proyecto'),
        ),
    ]
