# Generated by Django 3.2.7 on 2021-12-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0062_auto_20211202_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisitionbs',
            name='construcction',
        ),
    ]
