# Generated by Django 3.2.7 on 2021-12-02 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_alter_acquisitionbs_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionbs',
            name='comparative_chart',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Cuadro comparativo - estudio mercado'),
        ),
    ]
