# Generated by Django 3.2.7 on 2021-12-03 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0065_acquisitionbs_comparative_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informsuni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations_1', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº1')),
                ('inform_1', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº1')),
                ('observations_2', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº2')),
                ('inform_2', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº2')),
                ('observations_3', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº3')),
                ('inform_3', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº3')),
                ('observations_4', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº4')),
                ('inform_4', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº4')),
                ('observations_5', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº5')),
                ('inform_5', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº5')),
                ('observations_6', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº6')),
                ('inform_6', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº6')),
                ('observations_7', models.CharField(max_length=1000, verbose_name='Observaciones de seguimiento nº7')),
                ('inform_7', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de seguimiento nº7')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.construcction')),
            ],
        ),
        migrations.DeleteModel(
            name='DetHumansConst',
        ),
    ]
