# Generated by Django 3.2.7 on 2021-12-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0067_alter_informsuni_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetMaterialsConst',
        ),
    ]
