# Generated by Django 3.2.7 on 2021-12-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0068_delete_detmaterialsconst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisitionbs',
            options={'ordering': ['id'], 'verbose_name': 'Adquisición', 'verbose_name_plural': 'Adquisiciones'},
        ),
        migrations.AlterModelOptions(
            name='construcction',
            options={'ordering': ['id'], 'verbose_name': 'Construcción', 'verbose_name_plural': 'Construcciones'},
        ),
        migrations.AlterModelOptions(
            name='informsuni',
            options={'ordering': ['id'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='servicesp',
            options={'ordering': ['id'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
