# Generated by Django 3.2.7 on 2021-12-06 00:48

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0071_rename_offer_certification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managed',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=20000, null=True, verbose_name='Antecedentes del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ogeneral',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=65000, null=True, verbose_name='Detalle del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='treasurypdf/%Y/%m/%d', verbose_name='Archivo de Proyecto'),
        ),
    ]
