# Generated by Django 3.2.7 on 2021-12-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0073_auto_20211205_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['id'], 'verbose_name': 'Presupuesto_y_PAC', 'verbose_name_plural': 'Presupuestos_y_PACs'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['id'], 'verbose_name': 'Certificación', 'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_5',
            new_name='inform_five',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_4',
            new_name='inform_four',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_1',
            new_name='inform_one',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_7',
            new_name='inform_seven',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_6',
            new_name='inform_six',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_3',
            new_name='inform_three',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='inform_2',
            new_name='inform_two',
        ),
        migrations.RenameField(
            model_name='informsuni',
            old_name='observations_7',
            new_name='observations_seven',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_1',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_2',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_3',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_4',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_5',
        ),
        migrations.RemoveField(
            model_name='informsuni',
            name='observations_6',
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_five',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº5'),
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_four',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº4'),
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_one',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº1'),
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_six',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº6'),
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_three',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº3'),
        ),
        migrations.AddField(
            model_name='informsuni',
            name='observations_two',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº2'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='observations',
            field=models.CharField(max_length=1000, verbose_name='Presupuesto'),
        ),
    ]
