# Generated by Django 3.2.7 on 2021-12-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0074_auto_20211206_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informsuni',
            name='observations_seven',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones de seguimiento nº7'),
        ),
    ]
