# Generated by Django 3.2.7 on 2021-12-07 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_alter_informsuni_observations_seven'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisitionservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.CharField(max_length=1000, verbose_name='Observaciones de proyecto')),
                ('application', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud requirente - proyecto')),
                ('study', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Estudio de necesidad')),
                ('proforms', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Estudio de mercado / 3 proformas (archivo comprimido)')),
                ('autorization', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Autorización de solicitud de compra')),
                ('budget_request', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de certificación presupuestaria')),
                ('budget_certification', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación presupuestaria')),
                ('certification_pac', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación PAC')),
                ('certification_not_exist', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Certificación NO EXISTE en catálogo electrónico')),
                ('comparative_chart', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Cuadro comparativo - estudio mercado')),
                ('report_satisfaction', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Informe de satisfacción / Requirente proyecto')),
                ('enabling_documents', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documentos Habilitantes: RUC - CERT BANCARIA- COPIA CÉDULA')),
                ('payment_memorandum', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Memorando de Pago')),
                ('pay_order', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Orden de Pago')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Factura Electrónica mayor a 1000 USD')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione nombre del proyecto')),
            ],
            options={
                'verbose_name': 'Adquisición Servicio',
                'verbose_name_plural': 'Adquisición Servicios',
                'ordering': ['id'],
            },
        ),
    ]
