# Generated by Django 3.2.7 on 2021-12-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0076_acquisitionservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Construcction',
            new_name='ConstrucctionS',
        ),
    ]
