# Generated by Django 3.2.7 on 2021-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0077_rename_construcction_construcctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construcctions',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='construcctions',
            old_name='detail_amount',
            new_name='quantity_mount',
        ),
        migrations.AlterField(
            model_name='construcctions',
            name='namec',
            field=models.CharField(max_length=150, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='construcctions',
            name='organization',
            field=models.CharField(max_length=150, verbose_name='Entidad Ejecutora'),
        ),
        migrations.AlterField(
            model_name='construcctions',
            name='reshumans',
            field=models.CharField(max_length=150, verbose_name='Recursos Humanos'),
        ),
        migrations.AlterField(
            model_name='construcctions',
            name='results',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Resultados'),
        ),
    ]
