# Generated by Django 3.2.7 on 2021-12-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0078_auto_20211207_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConstrucctionS',
            new_name='Construcction',
        ),
        migrations.RenameField(
            model_name='construcction',
            old_name='namec',
            new_name='name',
        ),
    ]
