# Generated by Django 3.2.7 on 2021-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0080_auto_20211207_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='construcction',
            name='benefits',
            field=models.CharField(default=1, max_length=2000, verbose_name='Cliente Beneficiario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construcction',
            name='resmaterials',
            field=models.CharField(default=1, max_length=1000, verbose_name='Recursos Materiales'),
            preserve_default=False,
        ),
    ]
