# Generated by Django 3.2.7 on 2021-12-07 18:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0081_auto_20211207_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construcction',
            name='benefits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000, null=True, verbose_name='Cliente Beneficiario'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='resmaterials',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True, verbose_name='Recursos Materiales'),
        ),
    ]
