# Generated by Django 3.2.7 on 2021-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0082_auto_20211207_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construcction',
            name='benefits',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cliente Beneficiario'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='resmaterials',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Recursos Materiales'),
        ),
    ]
