# Generated by Django 3.2.7 on 2021-12-09 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0083_auto_20211207_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate',
            field=models.CharField(max_length=150, verbose_name='Número de Certificación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
