# Generated by Django 3.2.7 on 2021-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0087_auto_20211211_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['id'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=5000, verbose_name='Proyecto (*) '),
        ),
    ]
