# Generated by Django 3.2.7 on 2021-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0088_auto_20211211_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construcction',
            name='reshumans',
            field=models.CharField(blank=True, max_length=150000, null=True, verbose_name='Recursos Humanos'),
        ),
    ]
