# Generated by Django 3.2.7 on 2021-12-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0089_alter_construcction_reshumans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(help_text='10 characters max.', max_length=10, unique=True, verbose_name='Cédula de Identidad (*) '),
        ),
    ]
