# Generated by Django 3.2.7 on 2021-12-20 22:03

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0091_auto_20211216_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Proyecto (*) ')),
                ('organization', models.CharField(max_length=5000, verbose_name='Entidad Ejecutora (*) ')),
                ('type_project', models.CharField(max_length=5000, verbose_name='Tipo de Proyecto (*) ')),
                ('desing', models.CharField(max_length=5000, verbose_name='Diseño de Proyecto (*) ')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto del Proyecto')),
                ('quantity_mount', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Detalle del Monto')),
                ('reshumans', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Recursos Humanos')),
                ('managed', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='Antecedentes del Proyecto')),
                ('ogeneral', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='Detalle del Proyecto')),
                ('offer', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo Propuesta')),
                ('request_personal', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de personal')),
                ('request_material', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de material')),
                ('description', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Descripción')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateField(default=datetime.datetime.now, verbose_name='fecha de finalización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('process', models.BooleanField(verbose_name='Proceso')),
                ('results', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Resultados')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.represent', verbose_name='Administrador de Proyecto (*) ')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Perfilprod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_perfil', models.CharField(max_length=500, verbose_name='Tipo de Proyecto (*) ')),
                ('agreement', models.CharField(blank=True, max_length=7000, null=True, verbose_name='Convenio')),
                ('month', models.CharField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='Enero', max_length=20, null=True, verbose_name='Mes')),
                ('year', models.IntegerField(blank=True, max_length=4, null=True, unique=True, verbose_name='Año')),
                ('name', models.CharField(max_length=7000, verbose_name='1. Nombre del Proyecto (*)  ')),
                ('location', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='2. Localización geográfica')),
                ('analysis', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='3. Análisis de la situación actual (diagnóstico)')),
                ('record', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='4. Antecedentes')),
                ('justification', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='5. Justificación')),
                ('relation', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='6. Proyectos relacionados y / o complementarios')),
                ('objectivs', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='7. Objetivos')),
                ('goals', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='8. Metas')),
                ('activities', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='9. Actividades')),
                ('schedule', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='10. Cronograma de actividades')),
                ('duration', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='11.  Duración del proyecto y vida útil')),
                ('beneficiaries', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='12. Beneficiarios')),
                ('indicators', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='13. Indicadores de resultados alcanzados: cualitativos y cuantitativos')),
                ('impact', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='14. Impacto ambiental')),
                ('management', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='15. Autogestión y sostenibilidad')),
                ('framework', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='16. Marco institucional')),
                ('financing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='17. Financiamiento y análisis financiero del proyecto')),
                ('annexes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10485760, null=True, verbose_name='18. Anexos')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro (*) ')),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de inicio')),
                ('date_finish', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de finalización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('process', models.BooleanField(verbose_name='Proceso')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.represent', verbose_name='Responsable del Proyecto (*) ')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['id'],
            },
        ),
    ]
