# Generated by Django 3.2.7 on 2021-12-22 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0092_perfilprod_productive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Nombre de la Compra Pública (*) ')),
                ('offer', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='PAC Anual')),
                ('study', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Estudio de necesidad')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Certificación PAC')),
                ('comparative', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Cuadro Comparativo')),
                ('proforms', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Proformas')),
                ('catalogue', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Catálogo Electrónico')),
                ('order', models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', verbose_name='Orden de Compra')),
                ('description', models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Observación')),
                ('date_registration', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('date_start', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Compra')),
                ('date_finish', models.DateField(default=datetime.datetime.now, verbose_name='fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Hora de Actualización')),
                ('new', models.BooleanField(verbose_name='Nuevo')),
                ('finished', models.BooleanField(verbose_name='Cumplido')),
                ('process', models.BooleanField(verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Productivo',
                'verbose_name_plural': 'Productivos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='perfilprod',
            options={'ordering': ['id'], 'verbose_name': 'Perfilprod', 'verbose_name_plural': 'Perfilesprod'},
        ),
        migrations.AlterModelOptions(
            name='productive',
            options={'ordering': ['id'], 'verbose_name': 'Productivo', 'verbose_name_plural': 'Productivos'},
        ),
    ]
