# Generated by Django 3.2.7 on 2022-01-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0093_auto_20211222_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='construcction',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='construcction',
            name='proposal',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Propuesta No.'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='description',
            field=models.CharField(blank=True, max_length=255000, null=True, verbose_name='Descripción del documento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='documment',
            field=models.FileField(blank=True, null=True, upload_to='perfilprod/%Y/%m/%d', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='perfilprod',
            name='description',
            field=models.CharField(blank=True, max_length=255000, null=True, verbose_name='Descripción de documento'),
        ),
        migrations.AddField(
            model_name='perfilprod',
            name='documment',
            field=models.FileField(blank=True, null=True, upload_to='perfilprod/%Y/%m/%d', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='productive',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='productive',
            name='proposal',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Propuesta No.'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='Propuesta No.'),
        ),
        migrations.AlterField(
            model_name='acquisitionbs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='acquisitionservices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detsale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informsuni',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='finished',
            field=models.BooleanField(verbose_name='Finalizado'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicesp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
