# Generated by Django 3.2.7 on 2022-01-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0094_auto_20220107_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='construcction',
            name='desing',
            field=models.CharField(default=1, max_length=5000, verbose_name='Diseño de Proyecto (*) '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construcction',
            name='type_project',
            field=models.CharField(default=1, max_length=5000, verbose_name='Tipo de Proyecto (*) '),
            preserve_default=False,
        ),
    ]
