# Generated by Django 3.2.7 on 2022-01-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0095_auto_20220107_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesp',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.project', verbose_name='Seleccione nombre del proyecto (*)'),
            preserve_default=False,
        ),
    ]
