# Generated by Django 3.2.7 on 2022-01-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0096_servicesp_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesp',
            old_name='project',
            new_name='project_name',
        ),
    ]
