# Generated by Django 3.2.7 on 2022-01-24 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0098_auto_20220118_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='resignation',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Documento de renuncia o Solicitud de salida'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='state',
            field=models.CharField(max_length=150, verbose_name='Estado (*) '),
        ),
    ]
