# Generated by Django 3.2.7 on 2022-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0099_auto_20220124_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(help_text='10 characters max.', unique=True, verbose_name='Cédula de Identidad (*) '),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_emission',
            field=models.DateField(verbose_name='Fecha de emisión'),
        ),
    ]
