# Generated by Django 3.2.7 on 2022-02-20 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0100_auto_20220126_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publics',
            options={'ordering': ['id'], 'verbose_name': 'Compra Pública', 'verbose_name_plural': 'Compras Públicas'},
        ),
        migrations.AddField(
            model_name='represent',
            name='organization',
            field=models.CharField(default=1, max_length=5000, verbose_name='Institución (*) '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='represent',
            name='date_birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro (*) '),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
