# Generated by Django 3.2.7 on 2022-02-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0101_auto_20220220_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construcction',
            name='date_emission',
            field=models.DateField(verbose_name='Fecha de emisión'),
        ),
    ]
