# Generated by Django 3.2.7 on 2022-02-22 15:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0103_alter_construcction_date_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='represent',
            name='hour',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Emisión de Reporte'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Finalización de Proyecto'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='date_registration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro de Proyecto (*)'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio de Proyecto'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='finished',
            field=models.BooleanField(verbose_name='Proyecto Cumplido'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='new',
            field=models.BooleanField(verbose_name='Proyecto Nuevo'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='process',
            field=models.BooleanField(verbose_name='Proyecto en Proceso'),
        ),
        migrations.AlterField(
            model_name='construcction',
            name='results',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='Resultados de Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='date_finish',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Finalización de Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Inicio de Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='finished',
            field=models.BooleanField(verbose_name='Proyecto Cumplido'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='justification',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='5. Justificación del Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='new',
            field=models.BooleanField(verbose_name='Proyecto Nuevo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='process',
            field=models.BooleanField(verbose_name='Proyecto en Proceso'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='record',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='4. Antecedentes del Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='date_finish',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Finalización de Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='date_registration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro de Proyecto (*) '),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Inicio de Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='description',
            field=models.CharField(blank=True, max_length=255000, null=True, verbose_name='Descripción de Documento'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='finished',
            field=models.BooleanField(verbose_name='Proyecto Cumplido'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='justification',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='5. Justificación del Proyecto'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='new',
            field=models.BooleanField(verbose_name='Proyecto Nuevo'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='process',
            field=models.BooleanField(verbose_name='Proyecto en Proceso'),
        ),
        migrations.AlterField(
            model_name='perfilprod',
            name='record',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='4. Antecedentes del Proyecto'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Emisión de Reporte'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Finalización de Proyecto'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_registration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro de Proyecto (*)'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio de Proyecto'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='finished',
            field=models.BooleanField(verbose_name='Proyecto Cumplido'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='new',
            field=models.BooleanField(verbose_name='Proyecto Nuevo'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='process',
            field=models.BooleanField(verbose_name='Proyecto en Proceso'),
        ),
        migrations.AlterField(
            model_name='productive',
            name='results',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Resultados de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_emission',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Emisión de Reporte'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_finish',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Finalización de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_registration',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro de Proyecto (*) '),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Descripción de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.BooleanField(verbose_name='Proyecto Cumplido'),
        ),
        migrations.AlterField(
            model_name='project',
            name='new',
            field=models.BooleanField(verbose_name='Proyecto Nuevo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo de la Propuesta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.BooleanField(verbose_name='Proyecto en Proceso'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_material',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de Material'),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_personal',
            field=models.FileField(blank=True, null=True, upload_to='perfilpdf/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Solicitud de Personal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='results',
            field=models.CharField(blank=True, max_length=10485760, null=True, verbose_name='Resultados de Proyecto'),
        ),
    ]
