# Generated by Django 3.2.7 on 2022-02-22 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0104_auto_20220222_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='hour',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora de Registro (*) '),
        ),
        migrations.AlterField(
            model_name='represent',
            name='hour',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora de Registro (*) '),
        ),
    ]
