# Generated by Django 3.2.7 on 2022-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0106_auto_20220222_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Activo', 'activo'), ('Anulado', 'anulado')], default='Activo', max_length=30),
        ),
    ]
